export const enum Code {
  NO_CHANGED_VALUES = "NO_CHANGED_VALUES",
  DELETED = "DELETED",
  UN_AUTORIZED = "UN_AUTHORIZED",
  FORBIDDEN = "FORBIDDEN",
  NOT_FOUND = "NOT_FOUND",
  BAD_INPUT = "BAD_INPUT",
  SUCCESS = "SUCCESS",
  SMTH_WITH_DB = "SMTH_WITH_DB",
  EMAIL_USED = "EMAIL_USED",
}

export const enum valuesString {
  UPDATED = "UPDATED",
}

export enum UserType {
  USER = "USER",
  ADMIN = "ADMIN",
}
export enum BorrowStatus {
  BORROWED = "BORROWED",
  RETURNED = "RETURNED",
  OVERDUE = "OVERDUE",
}

export const enum ValidationErrors {
  NO_CHANGED_VALUES = "NO_CHANGED_VALUES",
  NO_SPACE_NO_SPECIAL_CHRACHTER = "NO_SPACE_NO_SPECIAL_CHRACHTER",
  INVALID_SKILL_LEVEL = "INVALID_SKILL_LEVEL",
  MUST_UNIQUE = "MUST_UNIQUE",
  REQUIRED = "REQUIRED",
  MUST_EMAIL = "MUST_EMAIL",
  MUST_8_CHRACHTERS = "MUST_8_CHRACHTERS",
  MUST_NUMBER = "MUST_NUMBER",
  MUST_STRING = "MUST_STRING",
  NUMBER_OUT_OF_RANGE = "NUMBER_OUT_OF_RANGE",
  STRING_OUT_OF_RANGE = "STRING_OUT_OF_RANGE",
  MUST_VALID_GENDER = "MUST_VALID_GENDER",
}
